// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/OA.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorAgentService_Get_FullMethodName  = "/proto.OrchestratorAgentService/Get"
	OrchestratorAgentService_Post_FullMethodName = "/proto.OrchestratorAgentService/Post"
)

// OrchestratorAgentServiceClient is the client API for OrchestratorAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorAgentServiceClient interface {
	Get(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetResponse, error)
	Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*Empty, error)
}

type orchestratorAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorAgentServiceClient(cc grpc.ClientConnInterface) OrchestratorAgentServiceClient {
	return &orchestratorAgentServiceClient{cc}
}

func (c *orchestratorAgentServiceClient) Get(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, OrchestratorAgentService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorAgentServiceClient) Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, OrchestratorAgentService_Post_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorAgentServiceServer is the server API for OrchestratorAgentService service.
// All implementations must embed UnimplementedOrchestratorAgentServiceServer
// for forward compatibility.
type OrchestratorAgentServiceServer interface {
	Get(context.Context, *Empty) (*GetResponse, error)
	Post(context.Context, *PostRequest) (*Empty, error)
	mustEmbedUnimplementedOrchestratorAgentServiceServer()
}

// UnimplementedOrchestratorAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorAgentServiceServer struct{}

func (UnimplementedOrchestratorAgentServiceServer) Get(context.Context, *Empty) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedOrchestratorAgentServiceServer) Post(context.Context, *PostRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Post not implemented")
}
func (UnimplementedOrchestratorAgentServiceServer) mustEmbedUnimplementedOrchestratorAgentServiceServer() {
}
func (UnimplementedOrchestratorAgentServiceServer) testEmbeddedByValue() {}

// UnsafeOrchestratorAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorAgentServiceServer will
// result in compilation errors.
type UnsafeOrchestratorAgentServiceServer interface {
	mustEmbedUnimplementedOrchestratorAgentServiceServer()
}

func RegisterOrchestratorAgentServiceServer(s grpc.ServiceRegistrar, srv OrchestratorAgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrchestratorAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorAgentService_ServiceDesc, srv)
}

func _OrchestratorAgentService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorAgentServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorAgentService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorAgentServiceServer).Get(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorAgentService_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorAgentServiceServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorAgentService_Post_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorAgentServiceServer).Post(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorAgentService_ServiceDesc is the grpc.ServiceDesc for OrchestratorAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OrchestratorAgentService",
	HandlerType: (*OrchestratorAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _OrchestratorAgentService_Get_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _OrchestratorAgentService_Post_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/OA.proto",
}
